[admin]
username = "admin"
password_hash = "$argon2id$v=19$m=19456,t=2,p=1$FVGhfDUHIQpSCUabKbhkVA$e0tpWtkmWL7uKmX2t517HOAHpUuBbmIpluFwDv522Ns" # admin123

[server]
host = "127.0.0.1"
port = 3000
base_url = "http://127.0.0.1:3000"

[database]
path = "./tts_data/database.db"

[storage]
static_path = "./static"
files_path = "./tts_data/files"
max_upload_size_mb = 1024

[jwt]
base_secret = "your-secret-key-change-in-production"
expiry_hours = 24
rotation_days = 30

[hashid]
min_length = 6

[siteinfo]
name = "TurtleShare"
author = "Admin"
avatar = ""
bio = "adminadminadmin"

[[siteinfo.social_links]]
platform = "github"
url = "https://github.com/takuron"

[[siteinfo.social_links]]
platform = "x"
url = "https://x.com/example"

[[siteinfo.social_links]]
platform = "bilibili"
url = "https://space.bilibili.com/12345"

[[siteinfo.social_links]]
platform = "telegram"
url = "https://t.me/example"

[[siteinfo.social_links]]
platform = "email"
url = "mailto:hello@example.com"
